name: Deploy React App

on:
  push:
    branches:
      - main # Replace with the name of the branch you want to deploy 1
jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        run: |
          yarn install
      - name: Build static files
        run: |
          yarn build
