name: Deploy React App

on:
  push:
    branches:
      - main # Replace with the name of the branch you want to deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to the server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/react-projects/meshit.kz &&
            git pull &&
            nvm use 18 &&
            node -v &&
            yarn install &&
            rm -rf dist/ &&
            echo "(ls -la)" &&
            yarn build &&
            echo "(ls -la)" &&
            cp -R dist/. /usr/share/nginx/html
